/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
volatile uint32_t *RCC_AHB1ENR = (volatile uint32_t *)0x40023830;//GPIOD CLK ENABLE add
volatile uint32_t *GPIOD_MODER = (volatile uint32_t *)0x40020C00;//GPIOD ENABLE OUTPUT add
volatile uint32_t *GPIOD_ODR   = (volatile uint32_t *)0x40020C14;//GPIOD ENABLE OUTPUT FOR PIN MANUAL-8.4.6 add
void lcd_command(unsigned char);
void LCD_SendNibble(unsigned char);
void LCD_EnablePulse();
void LCD_Data(unsigned char);
	int r;

	void delay(uint32_t count)
	{
	    volatile uint32_t i;

	    for(i = 0; i < count; i++);
	}
		void LCD_Init(void)
					{


					  /*
					    LCD Pin	Connection
1 VSS	GND
2 VDD	+5V
3 VO	Potentiometer middle pin
4 RS	PD0
5 RW	GND
6 EN	PD1
11 D4	PD2
12 D5	PD3
13 D6	PD4
14 D7	PD5
15 LED+	+5V
16 LED-	GND*/



			    delay(50000);

			    LCD_SendNibble(0x03); //LCD READY
			    delay(5000);

			    LCD_SendNibble(0x03);//LCD READY
			    delay(5000);

			    LCD_SendNibble(0x03);//LCD READY
			    delay(5000);

			    LCD_SendNibble(0x02);//4 BIT MODE
			    delay(5000);

			    lcd_command(0x28);   // 4-bit, 2-line,5X8 font
			    lcd_command(0x0C);   // Display ON, cursor off blink off
			    lcd_command(0x06);   // Entry mode cursor strt right
			    lcd_command(0x01);   // Clear display

			    delay(5000);

					}
		void LCD_EnablePulse(void)
							{
		    *GPIOD_ODR |= (1<<1);//enable the EN in the LCD
		    delay(10000);

		    *GPIOD_ODR &= ~(1<<1);
		    delay(10000);
							}
			void LCD_SendNibble(unsigned char nibble)
			{
			    *GPIOD_ODR &= ~(0x0F << 2);

			    if(nibble & 0x01)
			        *GPIOD_ODR |= (1 << 2);

			    if(nibble & 0x02)
			       *GPIOD_ODR |= (1 << 3);


			    if(nibble & 0x04)
			        *GPIOD_ODR |= (1 << 4);


			    if(nibble & 0x08)
			        *GPIOD_ODR |= (1 << 5);


			    LCD_EnablePulse();
			}
			void lcd_command(unsigned char cmd)
			{
			    *GPIOD_ODR &= ~(1<<0);// rs command to low

			    LCD_SendNibble(cmd>>4);//lcd high

			    delay(5000);

			    LCD_SendNibble(cmd&0x0F);// lcd low

			    delay(5000);


			}
			void LCD_Data(unsigned char data)
			{
			    *GPIOD_ODR |= (1<<0); //select writing enable RS in LCD

			    LCD_SendNibble(data>>4); //data right shift to 4 bits

			    delay(5000);

			    LCD_SendNibble(data&0x0F);

			    delay(5000);


			}

			void LCD_String(char *str)
			{
			    while(*str)
			    {
			        LCD_Data(*str);
			        str++;
			    }
			}

int main(void)
{
	  *RCC_AHB1ENR |= (1<<3);//enable clk for GIPIOD

	  *GPIOD_MODER &= ~(0xFFF);//RESET VALUE IN GIPOD
	  *GPIOD_MODER |= 0x555;//ENABLE OUTPUT FOR THE PD0-PD5

	    LCD_Init();

	    LCD_String("Hello Madhavan:)");

	    while(1)
	    {

	    }
}
